# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c37cd3c7f1e1f357002283bbf83325e02149effa91f4eed7657b9d83c1d0c4c56003e96c239cea6de2e98bab43762305a66aecd6aea3945712d08f6eaaa233f

test:
  secret_key_base: 773d0f27e8053dde1365f4f17c458bfc8c5f21bcae6dce686e521d59a2497a509d4b5f0366b8f93fc89bd33fa56cea8b28e07437560d821d4a7bb1dfb065e5b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
